### ISSUE TITLE
[ 需求 ] 新增 OpenAI API 代理站点的设置

### ISSUE THREAD

**Issue by B3nDan** [wxywb/history_rag#10]
因为某些情况下，不能直接访问 OpenAI ，需要使用国内网络可访问的 代理服务。
能否新增一个环境变量，例如 API_BASE_URL

**Comment by wxywb** [comment]
关于这个我看了一下，似乎是通过读取环境变量将openai的url换成某个proxy的地址，虽然我可以试试，但我没有这些代理地址，无法确认我是否做对，如果你可以成功，可以提交一个PR我来进行一些后处理？

**Comment by wxywb** [comment]
我大概看明白了，把你的apikey打个码吧

**Comment by wxywb** [comment]
你现在可以修改cfgs/config.yaml来使用api_base了
```yaml
llm:
    name: "gpt-4-0125-preview"
    temperature: 0.01
    api_base: "xxxxxxxxxxx"
```
